<h1 align="center">Julia Introduction</h1>

</br>

> Main Topics

```
- Basics
- Strings
- Data Structures
```

</br>

----

<h2>---- Basics ----</h2>

</br>

> Topics

```
- Variables, Printing and Comments
- Concatenation
- Simple Math
- Convertions
```

</br>

----

<b>- Variables, Printing and Comments</b>

In [1]:
# println >> prints a line and adds a \n at the end
# print   >> just prints a line without adding a \n at the end
println("Hello World, Julia!")
print("Hello World Again, Julia!")

Hello World, Julia!
Hello World Again, Julia!

----

In [2]:
my_null = nothing
typeof(my_null)

Nothing

In [68]:
my_bool1 = true
typeof(my_bool1)

Bool

In [69]:
my_bool2 = false
typeof(my_bool2)

Bool

In [2]:
my_integer = 42
typeof(my_integer)

Int64

In [3]:
my_float = 3.14159
typeof(my_float)

Float64

In [4]:
my_string = "hello world"
typeof(my_string)

String

In [25]:
my_char = 'a'
typeof(my_char)

Char

In [5]:
const my_const = "hello world again"
my_const = "you cannot reassign a value to a constant"

"you cannot reassign a value to a constant"

In [6]:
😄 = "Dunno why, but you can use emojis as variables names"
typeof(😄)

String

----

In [7]:
# this is a simple comment

In [8]:
#=

This is a multi-line
comment

=#

----

<b>- Concatenation</b>

In [9]:
# Do not do "Str1" + "Str2". Use "*" operator instead
"a" + "b" # throws an error

LoadError: MethodError: no method matching +(::String, ::String)
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:591

In [10]:
"a" * "b" # all right!

"ab"

----

<b>- Simple Math</b>

In [11]:
addition = 3 + 7

10

In [12]:
subtraction = 3 - 7

-4

In [13]:
multiplication = 3 * 7

21

In [14]:
quocient_division = 3 / 7

0.42857142857142855

In [15]:
power = 3 ^ 7

2187

In [16]:
modulus = 3 % 7

3

----

In [17]:
# Pi
pi

π = 3.1415926535897...

In [18]:
# Retrieves the last mathematical result
ans

π = 3.1415926535897...

----

<b>- Convertions</b>

In [19]:
# String to Integer
parse(Int64, "5")

5

In [20]:
# String to Float
parse(Float64, "5")

5.0

In [21]:
# Integer to String
string(5)

"5"

In [22]:
# Float to String
string(5.75)

"5.75"

In [23]:
# Float to Integer
floor(Int, 5.75)

5

In [24]:
# Integer to Float
float(5)

5.0

----

<h2>---- Strings ----</h2>

In [27]:
# Concatenation 1
string1 = "Hello"
string2 = "World"

print(string1 * " " * string2)

Hello World

In [28]:
# Concatenation 2
print("$string1 $string2")

Hello World

In [31]:
# Concatenation 3
number1 = "2"
number2 = "5"

print("$number1 times $number2 is equals $(number1 * number2)!!")

2 times 5 is equals 25!!

----

<h2>---- Data Structures ----</h2>

<b>1) Dictionaries</b>

In [45]:
# Creating a new dict
my_dict = Dict(
    "Dragon Ball"     => "Son Gohan"
    , "Demon Slayer"  => "Tomioka"
)

Dict{String, String} with 2 entries:
  "Demon Slayer" => "Tomioka"
  "Dragon Ball"  => "Son Gohan"

In [33]:
# Adding a new Key,Value
my_dict["JoJo"] = "Joseph Joeestar"

"Joseph Joeestar"

In [34]:
# Printing the Whole Dict
print(my_dict)

Dict("JoJo" => "Joseph Joeestar", "Demon Slayer" => "Tomioka", "Dragon Ball" => "Son Gohan")

In [35]:
# Printing a Single Value
print(my_dict["JoJo"])

Joseph Joeestar

In [36]:
# Getting a value and deleting it from the dict
# simultaneously
pop!(my_dict, "Dragon Ball")

"Son Gohan"

In [37]:
# Cheking out the dict
print(my_dict)

Dict("JoJo" => "Joseph Joeestar", "Demon Slayer" => "Tomioka")

In [40]:
# You cannot use indexes with dicts
# It will throws an error
print(my_dict[1])

LoadError: KeyError: key 1 not found

----

<b>2) Tuples</b>

In [41]:
# Creeating a new Tupple
my_tupple = ("Son Gohan", "Joseph Joestar", "Giyu Tomioka")

("Son Gohan", "Joseph Joestar", "Giyu Tomioka")

In [42]:
# Getting an elemnt
my_tupple[1] # yeeah guy, the indexes start from 1 in Julia...

"Son Gohan"

In [43]:
# You cannot change tupples values
my_tupple[1] = "Broly"

LoadError: MethodError: no method matching setindex!(::Tuple{String, String, String}, ::String, ::Int64)

----

<b>3) Arrays</b>

In [46]:
# Creating a new array
my_array = ["Son Gohan", "Giyu Tomioka", "Joseph Joestar"]

3-element Vector{String}:
 "Son Gohan"
 "Giyu Tomioka"
 "Joseph Joestar"

In [47]:
# Getting an Element
my_array[2]

"Giyu Tomioka"

In [48]:
# Changing a Value
my_array[1] = "Broly"

"Broly"

In [49]:
# Adding a New Element in the End
push!(my_array, "Midorya")

4-element Vector{String}:
 "Broly"
 "Giyu Tomioka"
 "Joseph Joestar"
 "Midorya"

In [56]:
# Adding more elements in the End
push!(my_array, "Levi", "King")

5-element Vector{String}:
 "Broly"
 "Giyu Tomioka"
 "Joseph Joestar"
 "Levi"
 "King"

In [50]:
# Deleting the last element
pop!(my_array)

"Midorya"

In [52]:
# Creating a random multi-dimensional array
rand(1, 2)

1×2 Matrix{Float64}:
 0.289987  0.422446

In [53]:
rand(2, 2)

2×2 Matrix{Float64}:
 0.324547  0.313218
 0.496036  0.75301

In [54]:
rand(3, 4, 5)

3×4×5 Array{Float64, 3}:
[:, :, 1] =
 0.583182  0.436061  0.191474  0.844967
 0.533269  0.599859  0.15122   0.726626
 0.424316  0.158449  0.252591  0.436083

[:, :, 2] =
 0.209069  0.921531  0.797179  0.360004
 0.379038  0.966754  0.336069  0.952579
 0.130137  0.795059  0.520042  0.463048

[:, :, 3] =
 0.22141   0.634862  0.246007   0.396561
 0.839932  0.998151  0.442637   0.133679
 0.321996  0.890397  0.0997657  0.443505

[:, :, 4] =
 0.0289659  0.196815  0.645269  0.576521
 0.479875   0.326686  0.419945  0.397132
 0.659632   0.828771  0.309346  0.690135

[:, :, 5] =
 0.506747  0.774507  0.409214  0.225668
 0.538873  0.936249  0.339577  0.00973742
 0.353143  0.80567   0.546404  0.439953

In [55]:
rand(3, 3, 3, 3)

3×3×3×3 Array{Float64, 4}:
[:, :, 1, 1] =
 0.258781  0.534321  0.868729
 0.54207   0.736511  0.227073
 0.309265  0.72661   0.289023

[:, :, 2, 1] =
 0.654474  0.558389  0.776221
 0.823403  0.228593  0.348566
 0.677061  0.181834  0.915591

[:, :, 3, 1] =
 0.759365  0.845011  0.137134
 0.701503  0.884788  0.165702
 0.256919  0.027112  0.859872

[:, :, 1, 2] =
 0.957802  0.539355  0.428501
 0.758876  0.563567  0.869047
 0.526478  0.376149  0.691874

[:, :, 2, 2] =
 0.951537  0.892188  0.856303
 0.826569  0.937119  0.760486
 0.109097  0.56733   0.881412

[:, :, 3, 2] =
 0.258719  0.8126    0.414196
 0.459101  0.77789   0.25954
 0.512242  0.760666  0.582628

[:, :, 1, 3] =
 0.519451   0.824215  0.25702
 0.0745692  0.409978  0.547743
 0.650494   0.548362  0.336597

[:, :, 2, 3] =
 0.86368   0.151144  0.74844
 0.461951  0.906512  0.674842
 0.233089  0.818154  0.434254

[:, :, 3, 3] =
 0.12551   0.322018  0.362092
 0.81807   0.236712  0.925705
 0.189553  0.109016  0.767397

In [57]:
# Creating array with zeros
zeros(2,2)

2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0

In [1]:
# Creating array with ones
ones(2, 2)

2×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0

In [62]:
# Creating arrays comprehension
rows = 3
columns = 3
my_array = [i + j for i in 1:rows, j in 1:columns]

3×3 Matrix{Int64}:
 2  3  4
 3  4  5
 4  5  6