<h1 align="center">Julia Introduction</h1>

</br>

> Main Topics

```
- Control Flow
```

</br>

----

<h2>---- Control Flow ----</h2>

<br />

> Topics:

```
- loops
- conditions
- functions
```

<b>1) Loops</b>

In [3]:
# While Loops
n = 0

while n < 10
    println(n)
    n += 1
end

0
1
2
3
4
5
6
7
8
9


In [7]:
# For Loop
for n in 0:10
    println(n)
end

0
1
2
3
4
5
6
7
8
9
10


In [9]:
# For Loop in Array
my_array = ["Gohan", "Giyu Tomioka", "Joseph Joestar"]

for character in my_array println(character) end

#=
for character in my_array
    println(character)
end
=#

Gohan
Giyu Tomioka
Joseph Joestar


----

<b>2) Conditions</b>

In [16]:
# If, Elseif, Else
number = 5

if number == 0 println("Zero")
elseif number < 0 println("Negative Number: $number")
else println("Positive Number: $number")
end

Positive Number: 5


In [17]:
# Ternary If
x = 5
y = 3
z = (x < y) ? x : y

3

In [18]:
# Ternary If with && Operator
(x > y) && println("$x is greather than $y")

5 is greather than 3


----
<b>3) Functions</b>

In [21]:
# Declaring a simple function
# There is no need to ad a "return" statement
function power(number)
    number^2
end

power(5)

25

In [22]:
# Declaring a lambda function
power(number) = number^2
power(5)

25

In [24]:
# Declaring a labmda function in a different way
# I rather the first one way
power_2 = number -> number^2
power_2(5)

25

----

In [25]:
# functions without "!" operator => does not changes
# the variable value
v = [3, 2, 6]

3-element Vector{Int64}:
 3
 2
 6

In [26]:
sort(v)

3-element Vector{Int64}:
 2
 3
 6

In [27]:
v

3-element Vector{Int64}:
 3
 2
 6

----

In [28]:
# Functions with "!" operator => changes the variables
# values. It is like the "inplacec=True" in Python
v = [3, 2, 6]

3-element Vector{Int64}:
 3
 2
 6

In [29]:
sort!(v)

3-element Vector{Int64}:
 2
 3
 6

In [30]:
v

3-element Vector{Int64}:
 2
 3
 6

----

In [9]:
# The dot operator (.) executes a function for each element from an array, matrix or dataframe
power_5(array) = array^5
array = rand(1:10, 2, 2)

2×2 Matrix{Int64}:
 8  5
 4  7

In [10]:
power_5.(array)

2×2 Matrix{Int64}:
 32768   3125
  1024  16807

----

<b>---- Help Function ----</b>

<br />

Like the `help` function in Python, we have `?` in Julia. See an example of how to search the documentation of `println` function.

In [1]:
?println

search: println printstyled print sprint isprint



```
println([io::IO], xs...)
```

Print (using [`print`](@ref)) `xs` to `io` followed by a newline. If `io` is not supplied, prints to the default output stream [`stdout`](@ref).

See also [`printstyled`](@ref) to add colors etc.

# Examples

```jldoctest
julia> println("Hello, world")
Hello, world

julia> io = IOBuffer();

julia> println(io, "Hello", ',', " world.")

julia> String(take!(io))
"Hello, world.\n"
```
